server:
  port: 8083
  servlet:
    context-path: /demo
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 971219
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
